version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./myconfig:/config
    environment:
      - TZ=Europe/Oslo
    restart: always
    network_mode: host
