version: '3.5'
services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: goodpassword
    volumes:
      - ./data:/var/lib/pgadmin
    ports:
      - '5050:80'
