version: '3.5'
services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-goodpassword}
      PGADMIN_ENABLE_TLS: ${PGADMIN_ENABLE_TLS:-}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - ./data:/var/lib/pgadmin
      - ./certs:/certs
    ports:
      - '5050:5050'
