# Set admin user name and password in .env file
version: '2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - /srv/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=home
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
