version: '2'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.4
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - /srv/influxdb/data:/var/lib/influxdb
